version: 2.1
orbs:
  macos: circleci/macos@2.0
jobs:
  test:
    macos:
        xcode: 14.3.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "eb:e1:59:78:03:cc:f6:6a:e4:bf:d4:63:13:f7:e5:78"
      - run:
          name: Set Git to use SSH
          command: |
            git config --global url."ssh://git@github.com".insteadOf "https://github.com"
      - checkout
      - switch-ruby:
          version: 2.7.5
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Install Fastlane
          command: bundle install
          working_directory: fastlane
      - run:
          name: Deploy with fastlane
          command: bundle exec fastlane ios internal_beta
          working_directory: fastlane
workflows:
  version: 2
  jest-test:
    jobs:
      - test
