version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.5-node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2f:09:c3:1f:a4:c7:b3:ea:ee:cc:59:d1:07:8d:39:5d"
      - run:
          name: Set Git to use SSH
          command: |
            git config --global url."ssh://git@github.com".insteadOf "https://github.com"
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Install Fastlane
          command: bundle install
          working_directory: fastlane
      - run:
          name: Deploy with fastlane
          command: bundle exec fastlane ios internal_beta
          working_directory: fastlane
workflows:
  version: 2
  jest-test:
    jobs:
      - test
