version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Deploy with fastlane
          command: bundle exec fastlane ios internal_beta
          working_directory: fastlane
workflows:
  version: 2
  jest-test:
    jobs:
      - test
