version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:14
jobs:
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Copy Environment Variables
          command: |
            echo $API_URL
            echo API_URL=$API_URL >> .env
            ls -a
            cat .env
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test
workflows:
  version: 2
  jest-test:
    jobs:
      - test
