version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.5-node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Install Fastlane
          command: bundle install
          working_directory: fastlane
      - run:
          name: Deploy with fastlane
          command: bundle exec fastlane ios internal_beta
          working_directory: fastlane
workflows:
  version: 2
  jest-test:
    jobs:
      - test
