version: 2.1
orbs:
  rn: react-native-community/react-native@7.1.1

commands:
  write-env-vars:
    description: "Write environment variables to .env.* file"
    parameters:
      envtype:
        type: string
      API_URL:
        type: env_var_name
      ENV:
        type: env_var_name
    steps:
      - run:
        name: Write environment variables to .env.* file
        command: |
          echo "<< parameters.API_URL >>=${<< parameters.API_URL >>}" >> .env.<< parameters.envtype >>
          echo "<< parameters.ENV >>=${<< parameters.ENV >>}" >> .env.<< parameters.envtype >>
jobs:
  test:
    executor:
      name: rn/macos
      xcode_version: 14.3.1
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - rn/yarn_install
      - rn/pod_install
      - run:
          name: Run Jest Tests
          command: yarn test
      - run:
          name: Install fastlane
          command: bundle install
          working_directory: fastlane
      - write-env-vars:
          envtype: staging
          API_URL: API_URL_STAGING
          ENV: ENV_STAGING
      - add_ssh_keys:
          fingerprints:
            - "eb:e1:59:78:03:cc:f6:6a:e4:bf:d4:63:13:f7:e5:78"
      - run:
          name: Bump Build
          command: yarn bump-build
      - run:
          name: Deploy with fastlane
          command: bundle exec fastlane ios internal_beta
          working_directory: fastlane
      - store_artifacts:
          path: output

workflows:
  test:
    jobs:
      - test