version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - run:
          name: Copy Environment Variables
          command: |
            echo API_URL=$API_URL >> .env
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test
workflows:
  version: 2
  jest-test:
    jobs:
      - test
