require 'dotenv/load'

platform :ios do

    lane :dev do

        # Set up match for development
        match(
            type: 'development',
            readonly: true
        )

        # Build
        gym(
            scheme: 'circleciRnTest-dev',
            export_method: 'development',
            workspace: './ios/circleciRnTest.xcworkspace',
            output_directory: './ios/build',
            output_name: 'circleciRnTest_dev.ipa'
        )

    end

    lane :internal_beta do

        # Configure circleci
        setup_circle_ci

        # Appstoreconnect API key for pilot to upload to TestFlight
        api_key = app_store_connect_api_key(
            key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
            issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
            key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT']
        )

        # Make sure match is set up correctly for the testflight deployment
        match(type: 'appstore', readonly: true)

        # Build
        gym(
            scheme: 'circleciRnTest-staging',
            export_method: 'app-store',
            workspace: './ios/circleciRnTest.xcworkspace',
            output_directory: './ios/build',
            output_name: 'circleciRnTest-staging.ipa'
        )

        # Upload to TestFlight
        pilot(
            skip_submission: true,
            skip_waiting_for_build_processing: true,
            username: 'aymather@gmail.com',
            app_identifier: 'com.example.circlecirntest',
            distribute_external: true,
            changelog: 'v#{get_version_number}(#{get_build_number})',
            beta_app_feedback_email: 'aymather@gmail.com',
            beta_app_description: 'v#{get_version_number}(#{get_build_number})',
            groups: ['memyselfandi']
        )

    end

end